<?php

if("0401" == gmdate('md'))
{
	$user['displayname'] = "Bruce";
	$user['sex'] = 0;
}

$id = isset($user['uid']) ? $user['uid'] : $user['id'];

if($id == 8)
	$user['lastknownbrowser'] = "Cynthetiq 0.31 on Windows 7 <!-- Cynthetiq/0.31 (Windows NT 6.1; U; en; .NET CLR 3.5.30729) -->";
else if($id == 1)
{
	$rndTitles = array(
		"12 herbs and spices!",
		"20% cooler than thou art",
		"20% cooler",
		"80's Cheerilee is best pony!",
		":3",
		"A bit of a failure",
		"A little bit beastly",
		"A man of wealth and taste",
		"A very very naughty boy!",
		"ACID3 is my personal sledgehammer",
		"Affected by a raging stiffie",
		"Always checks behind the chair",
		"Amateur Vidya Dev'r",
		"Ambidextrous Sprite",
		"Badass Furry",
		"Bec Noir",
		"Better than Blackhole",
		"Better with Bacon",
		"Better with Chocolate",
		"BL4R",
		"Board Programmer",
		"Brony",
		"Can Breathe in Space",
		"Catgirl Fanboi",
		"Ceci n'est pas une random title!",
		"Censor Decoy",
		"Coke&trade; Addict",
		"Confound these ponies, they drive me to drink.",
		"Contractually Immortal",
		"Dick Duck",
		"Don't. Even. Blink.",
		"Draco in Hotpants",
		"Draco in Leather Pants",
		"Duck my sick and yuck fou!",
		"Ensemble Darkhorse",
		"Ensemble Darkpony",
		"FMOD user",
		"Great and Powerful",
		"H3H3H3H",
		"Hard to label!",
		"Has a random title",
		"Has been working on the railroad",
		"I Am Iron Man",
		"I can't use these things together!",
		"I found Forrester and all I got was a random title",
		"I said, put the bunny back in the box!",
		"I was frozen today!",
		"I'm the one with the most talent here.",
		"Is gonna need more trope",
		"Is watching you clop clop clop",
		"It's a long story that involves a pi&ntilde;ata and a gun and a very naughty doggie&hellip;",
		"Keyboard Compatible!",
		"Large and In Charge",
		"Large Ham",
		"Local source of MSU1 information",
		"Lonely Man",
		"Lotus Eater",
		"Loves the whole world and all its' sights and sounds",
		"Lying Dutchman",
		"May contain nuts",
		"Mythbuster",
		"Natural Selection's gift to womankind",
		"Nazi science sneers at your custom titles!",
		"None of this makes any sense.",
		"Not a pony",
		"Not Richard Pryor",
		"Not the Messiah",
		"Now then, let's have a nice naked talk.",
		"Now with less self-mockery",
		"Now with more self-mockery",
		"Oatmeal? Are you <em>crazy?</em>",
		"OBJECTION!!",
		"Off Like a Shot",
		"Off-Model",
		"One of a kind!",
		"Put the bunny back in the box.",
		"Rainbow Dash",
		"Random Number God",
		"Random title!",
		"Rated M for Magikarp",
		"Rated M for Manly",
		"Rated M for Mental",
		"Rated M for Monkey",
		"Secretly, I am Andres Villareal",
		"Secretly, I'm Alan Rickman",
		"Secretly, I'm Alex Workman",
		"Secretly, I'm Andrew Hussie",
		"Secretly, I'm Charles Darwin",
		"Secretly, I'm Darles Charwin",
		"Secretly, I'm Derpy Hooves",
		"sEcReTlY, I'm GaMzEe MaKaRa",
		"Secretly, I'm Jean-Fran&ccedil;ois Lapointe",
		"Secretly, I'm Kevin Flynn",
		"Secretly, I'm Matvey Soloviev",
		"Secretly, I'm Patrick Stewart",
		"Secretly, I'm PZ Myers",
		"Secretly, I'm Rainbow Dash",
		"Secretly, I'm Richard Dawkins",
		"Secretly, I'm Robin Williams",
		"Secretly, I'm the Metaknight",
		"Secretly, I'm Thor Balle M&uuml;hlensteth",
		"Secretly, I'm William Shatner",
		"Shadowbolt",
		"Shinji Ikari",
		"SHOO-BE-DOO SHOO-SHOO-BE-DOO",
		"Tall, Dark and Bishoujo",
		"The best thing since bread glue",
		"The best thing since sliced bread",
		"The Brickshitter&trade;",
		"The Devilfucking Dickens",
		"The Signless",
		"The Snarkmeister",
		"The Sufferer",
		"The Thirteenth Doctor",
		"The Thirteenth Troll",
		"There's suspension of disbelief, and then there's insulting my fucking intelligence.",
		"Ties the room together",
		"Trollestia is Bestia",
		"TV Troper",
		"Universally genre savvy",
		"Upper Class Twit",
		"Watches you while you're sleeping",
		"What do you mean, it's not a random title?",
		"Why couldn't you put the bunny back in the box?",
		"Wonderbolt",
		"Would you care for a chocolate milk of glass?",
		"XNA user",
		"YEEEEAAAAH~!",
		"You read my title. That's enough social interaction for one day.",
		"You spin me right round baby right round like a record baby",
		"You're really messing with my Zen thing, man",
	);
	$user['title'] = $rndTitles[array_rand($rndTitles)];
}
else if($id == 13)
{
	$user['title'] = "Schr&ouml;dinger's cat is ".(rand(0, 100) < 50 ? "alive" : "dead");
}
?>